name = "api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.development]
vars = { ENVIRONMENT = "development" }

[env.staging]
name = "alq-staging"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "alq"
vars = { ENVIRONMENT = "production" }
